// LOCALHOST 
### GET local
GET http://localhost:8080/contacts 

### POST local
POST http://localhost:8080/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Jon", 
    "lastName": "smith 2.0", 
    "email": "Jsmith@test.com", 
    "favoriteColor":"Brown", 
    "birthday": "Jan 18"
}

### GET one local
GET http://localhost:8080/contacts/626a1a6564823af271730744

### PUT local
PUT http://localhost:8080/contacts/626a1932045889595fc6e6c3
Content-Type: application/json

{
    "firstName":"Jon", 
    "lastName":"Smitty", 
    "email":"Jsmith@test.com", 
    "favoriteColor":"Brown", 
    "birthday":"Jan 18"
}

### DELETE Local
DELETE http://localhost:8080/contacts/626a1a9764823af271730745







// PRODUCTION Deploy 
### GET Production
GET https://cse341api.herokuapp.com/contacts 

### POST Production
POST https://cse341api.herokuapp.com/contacts HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Jon", 
    "lastName": "smith 2.0", 
    "email": "Jsmith@test.com", 
    "favoriteColor": "Brown", 
    "birthday": "Jan 18"
}

### GET one Production
GET https://cse341api.herokuapp.com/contacts/626a1b28ce04b2a09597e8ba

### PUT Production
PUT https://cse341api.herokuapp.com/contacts/626a1b28ce04b2a09597e8ba
Content-Type: application/json

{
    "firstName":"Jon", 
    "lastName":"Smitty", 
    "email":"Jsmith@test.com", 
    "favoriteColor":"Green", 
    "birthday":"Jan 18"
}

### DELETE Production
DELETE https://cse341api.herokuapp.com/contacts/626a1b28ce04b2a09597e8ba